{
 "title": "HWiNFO Home Cluster",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Max Core Frequency",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(hw_core_clock_mhz) by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GPU Clock Mhz",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 0 },
   "targets": [
    { "expr": "hw_gpu_clock_mhz", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "hw_usage{category=\"CPU\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 16, "y": 0 },
   "targets": [
    { "expr": "hw_cpu_tctltdie_c", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Memory Load",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "hw_memory_load{sensor=\"Physical Memory Load\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mem Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 2, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "hw_memory_used_mb{category=\"Physical\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 2, "x": 22, "y": 0 },
   "targets": [
    { "expr": "hw_network_dl_rate_kbs", "legendFormat": " DL" },
    { "expr": "hw_network_up_rate_kbs", "legendFormat": " UP" }
   ]
  },
  {
   "title": "CPU Package Power (W)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hw_cpu_package_power_w", "legendFormat": "{{instance}} {{sensor}}" }
   ]
  },
  {
   "title": "GPU Power (W)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 3, "x": 4, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hw_gpu_power_w  ", "legendFormat": "{{instance}} {{sensor}}" }
   ]
  },
  {
   "title": "CPU + GPU Power Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 8 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    { "expr": "hw_cpu_package_power_w", "legendFormat": "{{instance}} CPU" },
    { "expr": "hw_gpu_power_w", "legendFormat": "{{instance}} GPU" }
   ]
  },
  {
   "title": "GPU Load",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 14, "y": 8 },
   "targets": [
    { "expr": "hw_gpu_core_load", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "GPU Temp",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 16, "y": 8 },
   "targets": [
    { "expr": "hw_gpu_temperature_c", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "GPU Fan",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 18, "y": 8 },
   "targets": [
    { "expr": "hw_gpu_fan", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "GPU Memory",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 2, "x": 20, "y": 8 },
   "targets": [
    { "expr": "hw_gpu_memory_allocated_mb", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Max I/O",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 22, "y": 8 },
   "targets": [
    {
     "expr": "max(hw_drive_total_activity) by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Annual Energy Consumption",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "expr": "(sum(hw_cpu_package_power_w) + sum(hw_gpu_power_w))*24*365/1000",
     "legendFormat": "Annual kWh Estimate"
    }
   ]
  },
  {
   "title": "Annual Cost Estimate",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 16 },
   "yaxes": [
    { "format": "currencyEUR" }
   ],
   "targets": [
    {
     "expr": "(sum(hw_cpu_package_power_w) + sum(hw_gpu_power_w))*(0.05+0.07)*24*365/1000"
    }
   ]
  },
  {
   "title": "CPU Throttle",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 16 },
   "targets": [
    {
     "expr": "sum(hw_cpu_thermal_throttling_yesno) by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "S.M.A.R.T.",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 16 },
   "targets": [
    {
     "expr": "sum(hw_drive_failure_yesno) by(instance) + sum(hw_drive_warning_yesno) by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Min Drive Remaining Life",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 16 },
   "targets": [
    {
     "expr": "min(hw_drive_remaining_life) by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}